toolbar:
  - bold italic | undo redo | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | paste
  - image | link
plugins:
  - image
  - link
  - lists
  - print
  - preview
  - searchreplace
  - visualblocks
  - fullscreen
  - insertdatetime
  - media
  - table
  - contextmenu
  - paste
  - code
paste_data_images: true
image_title: true
automatic_uploads: true
images_upload_url: 'postAcceptor.php'
file_picker_types: 'image'
