Category.create!([
  {description: "", parent_id: nil, title: "Кухонная мебель", slug: "kukhonnaia-mebel-0"},
  {description: "", parent_id: nil, title: "Камень. Каменные столешницы. Подоконники", slug: "kamen-kamennye-stoleshnitcy-podokonniki"}
])
FinishedOrder.create!([
  {order_number: 134}
])
Gallery.create!([
  {title: "Подоконники", category_id: 2, slug: "podokonniki", description: nil},
  {title: "Столешницы", category_id: 2, slug: "stoleshnitcy", description: ""}
])
Item.create!([
  {title: "Эко-плита CLEAF tss с термо-структурированной поверхностью Италия", description: "<p>Плиты TSS Cleaf - это новое поколение современных, экологически чистых конструкционно — отделочных материалов, получаемых особым способом прессования слоистых пластиков на древесные плиты.</p>\r\n<p>Отличительной особенностью продукта является ярко выраженная структура поверхности, имитирующая наличие глубоких пор, естественного спила дерева, ручной обработки древесины, тиснения в виде ткани, волн и других фантазийных поверхностей.</p>\r\n\r\n<p>\r\nПреимущества фасадов TSS:\r\n<ul>\r\n<li>сочетание визуального и тактильного эффектов</li>\r\n<li>устойчивость к царапинам и истиранию</li>\r\n<li>стойкость к загрязнению</li>\r\n<li>устойчивость к высоким температурам</li>\r\n<li>устойчивость к воздействию химических и чистящих веществ</li>\r\n<li>устойчивость к действию солнечных лучей</li>\r\n<li>экологичность (класс эмиссии формальдегидов Е1)</li>\r\n</ul>\r\n</p>", slug: "eko-plita-cleaf-tss-s-termo-strukturirovannoi-poverkhnost-iu-italiia", category_id: 1, price: "<ul>\r\n<li>1-я группа от 29 395 р. за 1 м.п.</li>\r\n<li>2-я группа от 32 150 р. за 1 м.п</li>\r\n<li>3-я группа от 35 850 р. за 1 м.п</li>\r\n</ul>\r\n\r\n<strong>В помплект входит:</strong>\r\n<ul>\r\n<li>Столешница пластик H=38 мм.</li>\r\n<li>Бортик пристеночный L=1000 мм.</li>\r\n<li>Цоколь наполный пластиковый L=1000 мм.</li>\r\n<li>Стол нижний 2-х дверный H=820 мм. Ширина 1000 мм.</li>\r\n<li>Шкаф верхний H=720 мм. Ширина 500 мм. - 2шт</li>\r\n</ul>"},
  {title: "Лакированный МДФ двухсторонний ALVIC \"Luxe\" высокий глянец/матовый Испания", description: "<p>Испанские высокоглянцевые и суперматовые плиты МДФ «LUXE от ALVIC” начали использыватся в производстве мебели относительно недавно, но достаточно быстро завоевывают прочные позиции. Производятся по уникальной инновационной технологии с применением лакокрасочных материалов УФ-лака, на самом современном оборудовании.</p>\r\n\r\n<p>\r\nОсновные характеристики плит ALVIC:\r\n<ul>\r\n<li>Высокая прочность поверхности</li>\r\n<li>Яркий сверкающий блеск</li>\r\n<li>Уникальная коллекция декоров</li>\r\n<li>Высокая светоустойчивость</li>\r\n<li>Возможность исправления мелких дефектов</li>\r\n<li>Комплексный продукт – плита + кромка + AL профиль и плита вставка для раздвижных дверей шкафов-купе</li>\r\n<li>Плитный материал удобен в раскрое</li>\r\n<li>Нет привязки к стандартным типоразмерам</li>\r\n<li>Продукция сертифицирована ISO 9001:2008 (сертификат, подтверждающий соответствие системе менеджмента качества)</li>\r\n<li>Продукция регулярно проходит проверку качества в независимой Лаборатории AIDIMA (Испания)</li>\r\n<li>Допустимые дефекты помечаются цветными стикерами, что значительно облегчает раскрой плит</li>\r\n</ul>\r\n</p>\r\n", slug: "lakirovannyi-mdf-dvukhstoronnii-alvic-luxe-vysokii-glianetc-matovyi-ispaniia", category_id: 1, price: "<ul> <li>Без текстуры от 31 800 р. за 1 м.п.</li> <li>С текстурой от 36 975 р. за 1 м.п</li> </ul> <strong>В помплект входит:</strong> <ul> <li>Столешница пластик H=38 мм.</li> <li>Бортик пристеночный L=1000 мм.</li> <li>Цоколь наполный пластиковый L=1000 мм.</li> <li>Стол нижний 2-х дверный H=820 мм. Ширина 1000 мм.</li> <li>Шкаф верхний H=720 мм. Ширина 500 мм. - 2шт</li> </ul>"},
  {title: "Пластик АКРИЛОВЫЙ односторонний AGT глянцевый/матовый Турция", description: "<p>\r\nОсобо популярными фасадами являются в последнее время фасады, выполненные из глянцевого полотна AGT. Данный материал заслужил такое признание благодаря своим характеристикам. Высокое качество продукции, применяемой для оформления любой мебели, не имеет аналогов. При этом широкий ассортимент, а также цветовая гамма дают возможность реализовать любые идеи в декорировании интерьера. Особо стоит отметить высокие эксплуатационные характеристики полотна AGT: влагостойкость, экологичность, устойчивость к внешним воздействиям. Благодаря особому составу глянцевого покрытия этого материала, осуществляется надежная защита поверхности от УФ лучей, от царапин.\r\n</p>", slug: "plastik-krilovyi-odnostoronnii-agt-gliantcevyi-matovyi-turtciia", category_id: 1, price: "<ul>\r\n<li>Без текстуры от 28 450 р. за 1 м.п.</li>\r\n<li>С текстурой от 34 530 р. за 1 м.п</li>\r\n</ul>\r\n\r\n<strong>В помплект входит:</strong>\r\n<ul>\r\n<li>Столешница пластик H=38 мм.</li>\r\n<li>Бортик пристеночный L=1000 мм.</li>\r\n<li>Цоколь наполный пластиковый L=1000 мм.</li>\r\n<li>Стол нижний 2-х дверный H=820 мм. Ширина 1000 мм.</li>\r\n<li>Шкаф верхний H=720 мм. Ширина 500 мм. - 2шт</li>\r\n</ul>"},
  {title: "Эмаль двух-компонентная. Поверхность устойчивая к износу.", description: "<p>Покрытие фасадов эмалью — один из популярных способов их декорирования. Если вы предпочитаете фигурные фасады с яркими узорами на обработанной поверхности — выбирайте эмаль. Благодаря проверенному процессу нанесения краски на плиту фасады сохраняют свой внешний вид надолго.</p>\r\n<p>\r\nСущественными преимуществами, важными для любой хозяйки являются:\r\n<ul>\r\n<li>Простота ухода. Крашеные фасады легко моются с помощью обычных моющих средств. Вам нет надобности приобретать специальные растворы для качественного ухода</li>\r\n<li>Поверхность фасадов не впитывает запахи, это ограничит вас от регулярного использования ароматизатора на кухне</li>\r\n<li>Устойчивость к влаге гарантирует сохранение первоначальных форм, отсутствие расслоения поверхности</li>\r\n<li>При длительном использовании такие фасады сохраняют внешний вид, не коробятся</li>\r\n</ul>\r\n</p>", slug: "emal-dvukh-komponentnaia-poverkhnost-ustoichivaia-k-iznosu", category_id: 1, price: "<ul>\r\n<li>Матовая от 30 670 р. за 1 м.п.</li>\r\n<li>Глянцевая от 36 230 р. за 1 м.п</li>\r\n<li>Металлик от 39 800 р. за 1 м.п</li>\r\n</ul>\r\n\r\n<strong>В помплект входит:</strong>\r\n<ul>\r\n<li>Столешница пластик H=38 мм.</li>\r\n<li>Бортик пристеночный L=1000 мм.</li>\r\n<li>Цоколь наполный пластиковый L=1000 мм.</li>\r\n<li>Стол нижний 2-х дверный H=820 мм. Ширина 1000 мм.</li>\r\n<li>Шкаф верхний H=720 мм. Ширина 500 мм. - 2шт</li>\r\n</ul>"},
  {title: "Массив \"Россия\". Берёза - дуб.", description: "<p>\r\nСалон - студия «lucky-line» предлагает изготовление кухни с фасадами из массива натурального дерева. Благородство, тепло и роскошь интерьера, где присутствует мебель из натурального дерева неоспоримо. При этом, для того, чтобы заказать кухонный гарнитур из массива, необязательно обладать большой кухней. Наши дизайнеры впишут в размеры Вашего помещения кухню из натурального дерева, используя те элементы, которые вместятся именно в Ваш интерьер. Красивые цвета натурального дерева и изысканные витрины с витражами сделают Вашу кухню уютной и комфортной.\r\nПри изготовлении кухонь из массива мы используем фасады российского производства Лорес и итальянского производства Stival.\r\n</p>", slug: "massiv-rossiia-bereza-dub", category_id: 1, price: "<ul>\r\n <li>\r\n \"Октавия\" \r\n  <ul>\r\n   <li>Берёза от 37 500 р. за 1 м.п.</li>\r\n   <li>Дуб от 40 700 р. за 1 м.п.</li>\r\n  </ul>\r\n </li>\r\n <li>\r\n <li>\r\n \"Лаура\" \r\n  <ul>\r\n   <li>Берёза от 40 600 р. за 1 м.п.</li>\r\n  </ul>\r\n </li>\r\n </li>\r\n\r\n <li>\r\n<li>\r\n \"Констанция\" \r\n  <ul>\r\n   <li>Берёза от 47 450 р. за 1 м.п.</li>\r\n   <li>Дуб от 49 800 р. за 1 м.п.</li>\r\n  </ul>\r\n </li>\r\n </li>\r\n</ul>\r\n\r\n<strong>В помплект входит:</strong>\r\n<ul>\r\n<li>Столешница пластик H=38 мм.</li>\r\n<li>Бортик пристеночный L=1000 мм.</li>\r\n<li>Цоколь наполный пластиковый L=1000 мм.</li>\r\n<li>Стол нижний 2-х дверный H=820 мм. Ширина 1000 мм.</li>\r\n<li>Шкаф верхний H=720 мм. Ширина 500 мм. - 2шт</li>\r\n</ul>"},
  {title: "Массив \"STIVAL\". Италия.", description: "<p>\r\n<ul style=\"list-style:none\">\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/Katalog_produktsii_STIVAL_2014.pdf\">Каталог продукции Stival 2014</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/Katalog-produktsii-RUSSTA-2017.pdf\">Каталог продукции Russta 2017</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/Iskusstvo-interera-ATTIMEC-2017.pdf\">Каталог продукции Attimec 2017</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/Stolovye_gruppy_ATTIMEC_2015.pdf\">Каталог продукции Attimec 2015</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/ITALION-catalog-20151.pdf\">Каталог продукции Italion 2015</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/katalog-elis.pdf\">Каталог Elis</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/novinki-italion.pdf\">Новинки Italion</a></li>\r\n<li><i class=\"fa fa-file-pdf-o\"></i> <a href=\"http://perfectstyle.by/wp-content/uploads/2015/06/Sistema-Tetris-2017.pdf\">Система Тетрис 2017</a></li>\r\n</ul>\r\n</p>", slug: "massiv-stival-italiia", category_id: 1, price: "<ul>\r\n<li>\"GT\" от 32 800 р. за 1 м.п.</li>\r\n<li>\"Скалли\" от 41 500 р. за 1 м.п</li>\r\n<li>\"Сандра-Ноче\" от 52 300 р. за 1 м.п</li>\r\n</ul>\r\n\r\n<strong>В помплект входит:</strong>\r\n<ul>\r\n<li>Столешница пластик H=38 мм.</li>\r\n<li>Бортик пристеночный L=1000 мм.</li>\r\n<li>Цоколь наполный пластиковый L=1000 мм.</li>\r\n<li>Стол нижний 2-х дверный H=820 мм. Ширина 1000 мм.</li>\r\n<li>Шкаф верхний H=720 мм. Ширина 500 мм. - 2шт</li>\r\n</ul>"}
])
NewsItem.create!([
  {title: "Новость #0", text: "№0 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #1", text: "№1 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #2", text: "№2 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #3", text: "№3 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #4", text: "№4 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #5", text: "№5 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #6", text: "№6 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #7", text: "№7 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."},
  {title: "Новость #8", text: "№8 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi."}
])
Opinion.create!([
  {name: "Отзыв #1", text: "№1 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #1", order_number: 101},
  {name: "Отзыв #2", text: "№2 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #2", order_number: 102},
  {name: "Отзыв #3", text: "№3 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #3", order_number: 103},
  {name: "Отзыв #4", text: "№4 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #4", order_number: 104},
  {name: "Отзыв #5", text: "№5 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #5", order_number: 105},
  {name: "Отзыв #6", text: "№6 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #6", order_number: 106},
  {name: "Отзыв #7", text: "№7 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #7", order_number: 107},
  {name: "Отзыв #8", text: "№8 Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                                Donec semper magna et ultricies semper. In maximus est a elit\n                                varius porttitor. Nunc vitae sapien facilisis, egestas magna sed,\n                                aliquet erat. Quisque nunc orci, gravida eu bibendum efficitur,\n                                laoreet sed ligula. Fusce varius fermentum nulla eu posuere.\n                                Pellentesque vel volutpat enim, semper sodales dui. Aenean cursus\n                                pharetra ultrices. Praesent sed odio nulla. Nunc sit amet risus\n                                et nulla consequat malesuada vel eu mauris. Fusce turpis nibh,\n                                venenatis ac sapien ac, tempor dapibus mi.", info: "Info of opinion #8", order_number: 108}
])
Order.create!([
  {name: "Name #0", phone_number: "+7 916 770 48 60", email: "email #0", item_id: nil},
  {name: "Name #1", phone_number: "+7 916 770 48 61", email: "email #1", item_id: nil},
  {name: "Name #2", phone_number: "+7 916 770 48 62", email: "email #2", item_id: nil},
  {name: "Name #3", phone_number: "+7 916 770 48 63", email: "email #3", item_id: nil},
  {name: "Name #4", phone_number: "+7 916 770 48 64", email: "email #4", item_id: nil},
  {name: "Name #5", phone_number: "+7 916 770 48 65", email: "email #5", item_id: nil},
  {name: "Name #6", phone_number: "+7 916 770 48 66", email: "email #6", item_id: nil},
  {name: "Name #7", phone_number: "+7 916 770 48 67", email: "email #7", item_id: nil},
  {name: "Name #8", phone_number: "+7 916 770 48 68", email: "email #8", item_id: nil},
  {name: "Сергей", phone_number: "89167704868", email: nil, item_id: nil},
  {name: "Сергей", phone_number: "89167704868", email: nil, item_id: nil}
])
Picture.create!([
  {imageable_type: "NewsItem", imageable_id: 176, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:21"},
  {imageable_type: "NewsItem", imageable_id: 176, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:22"},
  {imageable_type: "NewsItem", imageable_id: 176, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:22"},
  {imageable_type: "NewsItem", imageable_id: 176, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:22"},
  {imageable_type: "NewsItem", imageable_id: 177, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:23"},
  {imageable_type: "NewsItem", imageable_id: 177, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:23"},
  {imageable_type: "NewsItem", imageable_id: 177, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:23"},
  {imageable_type: "NewsItem", imageable_id: 177, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:24"},
  {imageable_type: "NewsItem", imageable_id: 178, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:24"},
  {imageable_type: "NewsItem", imageable_id: 178, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:24"},
  {imageable_type: "NewsItem", imageable_id: 178, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:24"},
  {imageable_type: "NewsItem", imageable_id: 178, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:25"},
  {imageable_type: "NewsItem", imageable_id: 179, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:25"},
  {imageable_type: "NewsItem", imageable_id: 179, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:25"},
  {imageable_type: "NewsItem", imageable_id: 179, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:26"},
  {imageable_type: "NewsItem", imageable_id: 179, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:26"},
  {imageable_type: "NewsItem", imageable_id: 180, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:26"},
  {imageable_type: "NewsItem", imageable_id: 180, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:26"},
  {imageable_type: "NewsItem", imageable_id: 180, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:27"},
  {imageable_type: "NewsItem", imageable_id: 180, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:27"},
  {imageable_type: "NewsItem", imageable_id: 181, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:27"},
  {imageable_type: "NewsItem", imageable_id: 181, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:28"},
  {imageable_type: "NewsItem", imageable_id: 181, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:28"},
  {imageable_type: "NewsItem", imageable_id: 181, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:28"},
  {imageable_type: "NewsItem", imageable_id: 182, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:28"},
  {imageable_type: "NewsItem", imageable_id: 182, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:29"},
  {imageable_type: "NewsItem", imageable_id: 182, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:29"},
  {imageable_type: "NewsItem", imageable_id: 182, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:29"},
  {imageable_type: "NewsItem", imageable_id: 183, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:29"},
  {imageable_type: "NewsItem", imageable_id: 183, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:30"},
  {imageable_type: "NewsItem", imageable_id: 183, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:30"},
  {imageable_type: "NewsItem", imageable_id: 183, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:30"},
  {imageable_type: "NewsItem", imageable_id: 184, image_file_name: "news1.jpg", image_content_type: "image/jpeg", image_file_size: 26792, image_updated_at: "2016-11-28 13:27:31"},
  {imageable_type: "NewsItem", imageable_id: 184, image_file_name: "news2.jpg", image_content_type: "image/jpeg", image_file_size: 47071, image_updated_at: "2016-11-28 13:27:31"},
  {imageable_type: "NewsItem", imageable_id: 184, image_file_name: "news3.jpg", image_content_type: "image/jpeg", image_file_size: 40927, image_updated_at: "2016-11-28 13:27:31"},
  {imageable_type: "NewsItem", imageable_id: 184, image_file_name: "news4.jpg", image_content_type: "image/jpeg", image_file_size: 46641, image_updated_at: "2016-11-28 13:27:31"}
])
